# repos:
#   - repo: local
#     hooks:
#       - id: mkdocs-build
#         name: Generate static site with mkdocs build
#         entry: bash -c 'task build'
#         language: system
#         types: [text]
#         stages: [commit, push, manual]
#         files: site/.*
