# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Justen Stall
site_description: |
  Justen Stall's portfolio and blog.
site_author: Justen Stall
site_url: https://justenstall.com
repo_url: https://github.com/justenstall/website
copyright: Copyright © 2023 Justen Stall

theme:
  name: material
  logo: assets/favicon-t-white-black.png
  favicon: assets/favicon-fullres.png
  language: en
  palette:
    # scheme: jstall
    # primary: custom
    # accent: custom
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      accent: custom
      toggle:
        icon: material/earth
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font:
    text: Inter
    code: DM Mono
  custom_dir: src/theme
  features:
    - content.code.copy
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.indexes

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/justenstall
    - icon: fontawesome/brands/github
      link: https://github.com/justenstall
    - icon: fontawesome/brands/slack
      link: https://cloud-native.slack.com/team/U026HE0JFEJ
  home:
    image: assets/justenstall.jpg
    description: |
      Data Science Engineer at the University of Dayton Research Institute.

extra_css:
  - stylesheets/colors.css
  - stylesheets/portfolio.css

docs_dir: src

plugins:
  - blog:
      draft_if_future_date: true
      categories_allowed:
        - General
  - social

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
