[tool.poetry]
name = "justenstall-github-io"
version = "0.0.1"
description = "Justen Stall's portfolio and blog."
authors = ["Justen Stall <justenstall@gmail.com>"]
readme = "README.md"
packages = [{include = "justenstall"}]

[tool.poetry.dependencies]
python = "^3.12"
mkdocs = "^1.5.3"
mkdocs-material = "^9.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
