[tool.poetry]
name = "justenstall-github-io"
version = "0.0.1"
description = "Justen Stall's portfolio and blog."
authors = ["Justen Stall <justenstall@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mkdocs = "^1.5.3"
mkdocs-material = {extras = ["imaging"], version = "^9.5.3"}
pygments = "^2.17.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
