# https://taskfile.dev

version: "3"

tasks:
  poetry:
    silent: true
    internal: true
    cmds:
      - command -v poetry > /dev/null

  install-deps:
    silent: true
    deps:
      - poetry
    cmds:
      - poetry install --no-root

  serve:
    deps: [install-deps]
    cmds:
      - poetry run mkdocs serve

  build:
    deps: [install-deps]
    cmds:
      - poetry run mkdocs build

  lint:
    cmds:
      - markdownlint-cli2
