# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task: serve

  serve:
    cmds:
      - uv run mkdocs serve

  build:
    cmds:
      - uv run mkdocs build

  lint:
    cmds:
      - npx markdownlint-cli2
