# This is the build workflow
name: Build

on:
  push:
    branches:
      - main
      - preview
  pull_request:
    branches-ignore:
      - main
      - preview
  workflow_call:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build 11ty site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true # images are stored with LFS
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "npm"
      - name: Install node dependencies
        run: npm install
      - name: Setup site cache
        uses: actions/cache@v3
        with:
          key: build-11ty-${{ github.run_id }}
          path: _site
          restore-keys: |
            build-11ty-
      - name: Build site with 11ty
        run: npm build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site/
          retention-days: 7
  deploy:
    name: Deploy site to GitHub Pages
    needs: build
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site/
      - name: Convert and upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
