name: Build

on:
  workflow_call:
    inputs:
      artifact:
        type: string
        required: true
      retention_days:
        type: number
        default: 1

jobs:
  build:
    name: mkdocs build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true # images are stored with LFS
      # From: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install poetry
        run: pipx install poetry==1.7.1
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: poetry
      # Install with --no-root because project does produce a python package
      - run: poetry install --no-root
      # From: https://github.com/squidfunk/mkdocs-material/blob/master/docs/publishing-your-site.md#with-github-actions
      - name: Setup MkDocs cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ github.run_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Build site with MkDocs
        run: poetry run mkdocs build
      - name: Upload build artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: site/
          retention-days: ${{ inputs.retention_days }}
