name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      do_release:
        description: "Create a release job?"
        default: false
        type: boolean

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true # images are stored with LFS
      # From: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install poetry
        run: pipx install poetry==1.7.1
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: poetry
      # Install with --no-root because project does produce a python package
      - run: poetry install --no-root
      # From: https://github.com/squidfunk/mkdocs-material/blob/master/docs/publishing-your-site.md#with-github-actions
      - name: Setup MkDocs cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ github.run_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Build site with MkDocs
        run: poetry run mkdocs build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/
          retention-days: 7
  deploy:
    name: Deploy site to GitHub Pages
    needs: build
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site/
      - name: Convert and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  release:
    name: Release
    needs: build
    if: ${{ inputs.do_release }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/setup-node@v4
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
