name: CI

on:
  push:
    branches:
      - main
    paths:
      # mkdocs source
      - "src/**"
      - "mkdocs.yml"
      # poetry source
      - "pyproject.toml"
      - "poetry.lock"
      # run updated workflows
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - "mkdocs.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      do_release:
        description: "Create a release?"
        default: false
        type: boolean
  # Run the workflow every Monday at 8am
  schedule:
    - cron: "0 8 * * 1"

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ############################################################
  # Lints Markdown files
  ############################################################
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xt0rted/markdownlint-problem-matcher@v2
      - uses: DavidAnson/markdownlint-cli2-action@v14
        continue-on-error: true

  ############################################################
  # Build the site with MkDocs
  ############################################################
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact: site

  ############################################################
  # Deploys the site to GitHub Pages
  ############################################################
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      artifact: site

  ############################################################
  # Triggers a release with Semantic Release
  ############################################################
  release:
    needs: deploy
    # Release when requested and on scheduled workflows
    # This guarantees dependency upgrades get deployed at least once a week
    if: ${{ inputs.do_release || github.event == 'schedule' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install poetry # Needed for updating version in pyproject.toml
        run: pipx install poetry==1.7.1
      - name: List semantic release plugins
        id: listPlugins
        uses: mikefarah/yq@master
        with:
          cmd: yq '[ .plugins[] | .[0] // . ] | join(" ")' .releaserc
      - name: Install Semantic Release plugins
        run: npm install -g ${{ steps.listPlugins.outputs.result }}
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  ############################################################
  # Analyze code with CodeQL
  ############################################################
  analyze:
    needs: build
    uses: ./.github/workflows/codeql.yml
    # Only run this job on scheduled workflows (it takes a while)
    if: ${{ github.event == 'schedule' }}
    with:
      artifact: site
