# Defines a generic deployment workflow to be reused for multiple environments
name: "Deploy site to GitHub Pages"

on:
  workflow_call:
    outputs:
      page_url:
        description: The URL at which the preview has been deployed
        value: ${{ jobs.deploy.outputs.page_url }}

jobs:
  deploy:
    name: Deploy site to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
      pull-requests: write # to leave comment on PR
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v4
      - name: Download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: site/
      - name: Convert and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: ${{ github.ref_name != github.event.repository.default_branch }}
      - name: Updating PR with link to preview deployment
        if: ${{ github.ref_name != github.event.repository.default_branch }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: "Deployed a preview of ${{ github.sha }} to <${{ steps.deployment.outputs.page_url }}>"
          hide_and_recreate: true
          hide_classify: "OUTDATED"
