name: Deploy

on:
  workflow_call:
    inputs:
      artifact:
        type: string
        required: true
    outputs:
      page_url:
        description: The URL at which the preview has been deployed
        value: ${{ jobs.deploy.outputs.page_url }}

jobs:
  deploy:
    name: Deploy
    if: ${{ github.ref_name == github.event.repository.default_branch }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      # directory that artifact is downloaded to
      # and deployed from
      workdir: "site"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write # to deploy to pages
      id-token: write # unsure
      pull-requests: write # to leave comment on PR
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v4
      - name: Download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: ${{ env.workdir }}
      - name: Convert and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.workdir }}
      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
